/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Wave.h"
/* Header for class com_lyyjy_zdhyjs_bluetoothfish_WaveControler */

#ifndef _Included_com_lyyjy_zdhyjs_bluetoothfish_WaveControler
#define _Included_com_lyyjy_zdhyjs_bluetoothfish_WaveControler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyyjy_zdhyjs_bluetoothfish_WaveControler
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_createCClass
  (JNIEnv *, jobject,jobject bitmap);

JNIEXPORT jint JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_createCClassWithScale
        (JNIEnv *, jobject,jobject bitmap,jfloat scale);

JNIEXPORT void JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_deleteCClass
        (JNIEnv *, jobject,Wave* pAddress);

JNIEXPORT void JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_rippleBitmap
        (JNIEnv *, jobject,jobject bitmap,Wave* pAddress);

JNIEXPORT void JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_setSourcePower
        (JNIEnv *, jobject,float x ,float y, Wave* pAddress);

//设置波源大小
JNIEXPORT void JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_setSourcePowerSize
        (JNIEnv *, jobject,jint radius,jint depth,Wave* pAddress);

//水面滑动
JNIEXPORT void JNICALL Java_com_lyyjy_zdhyjs_bluetoothfish_WaveControler_moveLine
        (JNIEnv *, jobject,jfloat startX,jfloat startY,jfloat endX,jfloat endY,Wave* pAddress);
#ifdef __cplusplus
}
#endif
#endif
